const path = require('path');

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function relativeUrl(fromFile, assetPath) {
  return path.relative(path.dirname(fromFile), assetPath).split(path.sep).map(encodeURIComponent).join('/');
}

function previewCard(previewPath, item) {
  const canRender = item.format === 'png' || item.format === 'svg' || item.format === 'ico';
  const size = item.sizes ? `${item.sizes.join(', ')}px` : item.size ? `${item.size}px` : 'metadata';
  const body = canRender
    ? `<img src="${relativeUrl(previewPath, item.path)}" alt="${escapeHtml(path.basename(item.path))}">`
    : `<div class="file">${escapeHtml(item.format.toUpperCase())}</div>`;
  return `<article class="card">
    <div class="sample">${body}</div>
    <strong>${escapeHtml(path.basename(item.path))}</strong>
    <span>${escapeHtml(item.target)} · ${escapeHtml(item.format)} · ${escapeHtml(size)}</span>
  </article>`;
}

function renderPreviewHtml(cwd, previewPath, config, produced) {
  const title = config.project?.name || path.basename(cwd);
  const cards = produced.map((item) => previewCard(previewPath, item)).join('\n');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} icon preview</title>
  <style>
    :root { color-scheme: light dark; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { margin: 0; padding: 32px; background: #f6f7f9; color: #12151c; }
    h1 { margin: 0 0 8px; font-size: 28px; line-height: 1.1; letter-spacing: 0; }
    p { margin: 0 0 24px; color: #5d6675; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(176px, 1fr)); gap: 16px; }
    .card { display: grid; gap: 10px; align-content: start; min-height: 206px; padding: 14px; border: 1px solid #d9dee7; border-radius: 8px; background: #fff; }
    .sample { display: grid; place-items: center; height: 128px; border-radius: 6px; background-color: #fff; background-image: linear-gradient(45deg, #d8dde6 25%, transparent 25%), linear-gradient(-45deg, #d8dde6 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #d8dde6 75%), linear-gradient(-45deg, transparent 75%, #d8dde6 75%); background-size: 20px 20px; background-position: 0 0, 0 10px, 10px -10px, -10px 0; overflow: hidden; }
    img { max-width: 96px; max-height: 96px; image-rendering: auto; }
    strong { font-size: 14px; line-height: 1.2; word-break: break-word; }
    span { font-size: 12px; color: #687384; }
    .file { display: grid; place-items: center; width: 76px; height: 76px; border: 1px solid #b9c1cf; border-radius: 6px; background: #eef1f6; color: #485366; font-weight: 700; font-size: 13px; }
    @media (prefers-color-scheme: dark) {
      body { background: #11151d; color: #f6f7f9; }
      p, span { color: #a5afbf; }
      .card { background: #171d27; border-color: #2d3543; }
      .sample { background-color: #141a23; background-image: linear-gradient(45deg, #303849 25%, transparent 25%), linear-gradient(-45deg, #303849 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #303849 75%), linear-gradient(-45deg, transparent 75%, #303849 75%); }
      .file { background: #222a37; border-color: #485366; color: #cbd5e1; }
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)} icon preview</h1>
  <p>Generated by icon-maker. Check tiny sizes first, then app/store surfaces.</p>
  <main class="grid">
${cards}
  </main>
</body>
</html>
`;
}

module.exports = { renderPreviewHtml };
